#ifndef __Macro_H__
#define __Macro_H__

#define IMAGE_StartScene			"background/StartScene.jpg"
#define IMAGE_GameAboutBackground	"background/GameAboutBackground.png"
#define IMAGE_levelBackground		"background/levelBackground.png"

#define IMAGE_GameStartItem			"title/GameStartItem.png"
#define IMAGE_GameStartItem2		"title/GameStartItem2.png"
#define IMAGE_GameIntroduce			"title/GameIntroduce.png"
#define IMAGE_GameIntroduce2		"title/GameIntroduce2.png"
#define IMAGE_GameExit				"title/GameExit.png"
#define IMAGE_GameExit2				"title/GameExit2.png"
#define IMAGE_go					"title/go.png"
#define IMAGE_go2					"title/go2.png"
#define IMAGE_switchWord			"title/switchWord"

#define MAP_Round					"level/Round"

#define IMAGE_back_normal			"paddle/back_normal.png"
#define IMAGE_back_press			"paddle/back_press.png"
#define IMAGE_back_normal_white		"paddle/back_normal_white.png"
#define IMAGE_back_press_white		"paddle/back_press_white.png"
#define IMAGE_LEFT_1				"paddle/left.png"
#define IMAGE_LEFT_2				"paddle/left_press.png"
#define IMAGE_RIGHT_1				"paddle/right.png"
#define IMAGE_RIGHT_2				"paddle/right_press.png"
#define IMAGE_UP_1					"paddle/top.png"
#define IMAGE_UP_2					"paddle/top_press.png"
#define IMAGE_DOWN_1				"paddle/buttom.png"
#define IMAGE_DOWN_2				"paddle/buttom_press.png"
#define IMAGE_fire					"paddle/fire.png"
#define IMAGE_fire2					"paddle/fire_press.png"
#define IMAGE_People				"paddle/People.png"
#define IMAGE_bigFireButton			"paddle/bigFireButton.png"
#define IMAGE_bigFireButton2		"paddle/bigFireButton2.png"

#define IMAGE_playerU				"tank/player1/playerU.png"
#define IMAGE_enemy1D				"tank/enemy/enemy1D.png"
#define IMAGE_enemy2D				"tank/enemy/enemy2D.png"
#define IMAGE_enemy3D				"tank/enemy/enemy3D.png"
#define IMAGE_enemy4D				"tank/enemy/enemy4D.png"
#define IMAGE_heroBullet			"tank/bullet/heroBullet.png"
#define IMAGE_enemyBullet			"tank/bullet/enemyBullet.png"
#define IMAGE_bigFire				"tank/bullet/bigFire.png"			
#define IMAGE_bigFire2				"tank/bullet/0.png"			
#define IMAGE_bigFire3				"tank/bullet/1006-1.png"	

#define IMAGE_tishi					"hint/tishi.png"
#define IMAGE_tishi2				"hint/tishi2.png"
#define IMAGE_tishiNoGo				"hint/tishiNoGo.png"
#define IMAGE_continueGame			"hint/continueGame.png"
#define IMAGE_continueGame2			"hint/continueGame2.png"
#define IMAGE_quitGame				"hint/quitGame.png"
#define IMAGE_quitGame2				"hint/quitGame2.png"
#define IMAGE_noLeaveName1			"hint/noLeaveName1.png"
#define IMAGE_noLeaveName2			"hint/noLeaveName2.png"
#define IMAGE_anniuTouch			"hint/anniuTouch.png"
#define IMAGE_quanTouch				"hint/quanTouch.png"
#define IMAGE_upScore1				"hint/upScore1.png"
#define IMAGE_upScore2				"hint/upScore2.png"
#define IMAGE_winTitle				"hint/winTitle.png"
#define IMAGE_shuButton				"hint/shuButton.png"
#define IMAGE_shangchuan			"hint/shangchuan.png"
#define IMAGE_upScoreFalse			"hint/upScoreFalse.png"
#define IMAGE_hintEnter				"hint/hintEnter.png"

#define IMAGE_life					"prop/life.png"
#define IMAGE_sha					"prop/sha.png"
#define IMAGE_boss					"prop/boss.png"
#define IMAGE_addfire				"prop/addfire.png"
#define IMAGE_stop					"prop/stop.png"
#define IMAGE_strongFire			"prop/strongFire.png"
#define IMAGE_nextLevel				"prop/nextLevel.png"
#define IMAGE_editBox				"prop/editBox.png"

#define IMAGE_blast					"blast"
#define PLIST_blast					"prop/blast.plist"


#define IMAGE_StartPeople			"logo/StartPeople.png"
#define IMAGE_StartPeople2			"logo/StartPeople2.png"
#define IMAGE_wife					"logo/wife.png"

#define MUSIC_shoot					"sounds/shoot.wav"
#define MUSIC_background			"sounds/background.mp3"
#define MUSIC_startMusic			"sounds/startMusic.mp3"
#define MUSIC_eat1					"sounds/eat1.wav"
#define MUSIC_eat2					"sounds/eat2.wav"
#define MUSIC_gameover				"sounds/gameover.wav"

#define IMAGE_store1				"pay/store1.png"
#define IMAGE_store2				"pay/store2.png"
#define IMAGE_payTitle				"pay/payTitle.png"
#define IMAGE_titlePayFire1			"pay/titlePayFire1.png"
#define IMAGE_titlePayFire2			"pay/titlePayFire2.png"
#define IMAGE_titlePayFire3			"pay/titlePayFire3.png"
#define IMAGE_payFire1_1			"pay/payFire1_1.png"
#define IMAGE_payFire1_2			"pay/payFire1_2.png"
#define IMAGE_payFire1_3			"pay/payFire1_3.png"
#define IMAGE_payFire2_1			"pay/payFire2_1.png"
#define IMAGE_payFire2_2			"pay/payFire2_2.png"
#define IMAGE_payFire2_3			"pay/payFire2_3.png"
#define IMAGE_payFire3_1			"pay/payFire3_1.png"
#define IMAGE_payFire3_2			"pay/payFire3_2.png"
#define IMAGE_payFire3_3			"pay/payFire3_3.png"

#define IMAGE_blankItem				"blankItem.png"
#define XML_levelItem				"levelItem.xml"

#endif